# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    command:
      [
        "mysqld",
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8",
        "--collation-server=utf8_spanish_ci",
      ]
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - /usr/share/zoneinfo/America/Bogota:/etc/localtime
      - ~/.mysql-docker:/var/lib/mysql
      - ./Scripts/qualityControlDB.sql:/docker-entrypoint-initdb.d/0_init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

  web:
    build: ./nginx
    restart: always
    volumes:
      - /usr/share/zoneinfo/America/Bogota:/etc/localtime
      - ../frontQuality/dist/frontQuality:/var/www/html/angular
    ports:
      - "80:80"
      - "443:443"

  node:
    image: node
    restart: always
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
