# Use root/example as user/password credentials
version: "3.1"

services:
  web:
    build: ./nginx
    restart: always
    volumes:
      - /usr/share/zoneinfo/America/Bogota:/etc/localtime
      - dist/SQLfrontQuality/:/var/www/html/angular
    ports:
      - "80:80"
      - "443:443"
